server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      # Frontend birbaşa (file:// və ya başqa origin) açıldıqda CORS preflight-ı qəbul et.
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:

        # POST /api/urls -> url-service (yeni link qısaltmaq üçün)
        - id: url-service-api
          uri: lb://url-service
          predicates:
            - Path=/api/urls/**

        # GET /api/analytics/{shortCode} -> analytics-service
        - id: analytics-service-api
          uri: lb://analytics-service
          predicates:
            - Path=/api/analytics/**

        # GET /{shortCode} -> url-service (redirect üçün)
        - id: url-service-redirect
          uri: lb://url-service
          predicates:
            - Path=/{shortCode}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
